# Numpy Introduction

### Array types and Creating Numpy Arrays

In [2]:
import numpy as np

In [4]:
integers = np.array([10,20,30,40,50])

In [6]:
print(integers)

[10 20 30 40 50]


In [7]:
integers[0]

10

In [8]:
integers[0] = 20
integers

array([20, 20, 30, 40, 50])

In [9]:
integers[0] = 21.5
integers

array([21, 20, 30, 40, 50])

In [10]:
integers.dtype

dtype('int64')

In [11]:
smallerIntegers = np.array(integers, dtype = np.int8)
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [13]:
integers.nbytes

40

In [15]:
smallerIntegers.nbytes

5

In [17]:
overflow = np.array([127,128, 129], dtype=np.int8)
overflow

/var/folders/y4/12q38qbd5hs7h8842l8c6h3m0000gn/T/ipykernel_67870/3132148696.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  overflow = np.array([127,128, 129], dtype=np.int8)
/var/folders/y4/12q38qbd5hs7h8842l8c6h3m0000gn/T/ipykernel_67870/3132148696.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  overflow = np.array([127,128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

In [18]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])
print(floats)

[1.2 2.3 3.4 5.1 8.3]


In [19]:
floats.dtype

dtype('float64')

### Multidimensional arrays

<img src='mult_arrays.png' alt='mult_arrays' width=400>

In [21]:
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
nums[0][0]

1

In [24]:
nums[1,4]

10

In [25]:
nums.ndim

2

In [28]:
multi_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
multi_arr[1,0,2]

9

### Creating arrays from Lists and other Python structures

In [31]:
first_list = [1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [33]:
first_arrays = np.array(first_list)
first_arrays

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
second_list=[1,2,3,-1.23,50,128000.56,4.56]

In [35]:
second_array=np.array(second_list)

In [37]:
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [38]:
second_array.dtype

dtype('float64')

In [39]:
third_list = ['Ann',111111,'Peter',111112,'Susan',111113,'John',111114]

In [40]:
third_array=np.array(third_list)

In [41]:
third_array

array(['Ann', '111111', 'Peter', '111112', 'Susan', '111113', 'John',
       '111114'], dtype='<U21')

In [42]:
first_tuple = (5,10,15,20,25,30)

In [43]:
array_from_tuple=np.array(first_tuple)

In [44]:
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [45]:
array_from_tuple.dtype

dtype('int64')

In [46]:
multi_dim_list=[[[0,1,2], [3,4,5]], [[6,7,8],[9,10,11]]] 

In [47]:
arr_from_multi_dim_list=np.array(multi_dim_list)

In [48]:
arr_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Intrinsic Numpy array creation

In [50]:
integers_array = np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
second_array=np.arange(100,130)
second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [52]:
third_array=np.arange(100,130,2)
third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128])

In [53]:
floats_arr=np.linspace(10,20)
floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [54]:
floats_arr=np.linspace(10,20,5)
floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [56]:
rand_arr=np.random.rand(10)
rand_arr

array([0.21731469, 0.40065081, 0.65487101, 0.1622517 , 0.52935314,
       0.82424191, 0.66577762, 0.32534495, 0.80470442, 0.69893385])

In [57]:
rand_arr=np.random.rand(4,4)
rand_arr

array([[0.59114909, 0.59196537, 0.26331248, 0.03830605],
       [0.51526533, 0.70999687, 0.73280113, 0.68687378],
       [0.72364185, 0.73871944, 0.66002261, 0.14188418],
       [0.95225737, 0.09932842, 0.1406752 , 0.06723795]])

In [59]:
rand_arr=np.random.randint(0,100,20)
rand_arr

array([70, 15, 36, 92, 70, 17, 85, 58, 24, 72, 20, 64, 79, 96, 47, 84, 90,
       86, 38, 64])