# Numpy Introduction

### Array types and Creating Numpy Arrays

In [2]:
import numpy as np

In [3]:
integers = np.array([10,20,30,40,50])

In [4]:
print(integers)

[10 20 30 40 50]


In [5]:
integers[0]

10

In [6]:
integers[0] = 20
integers

array([20, 20, 30, 40, 50])

In [7]:
integers[0] = 21.5
integers

array([21, 20, 30, 40, 50])

In [8]:
integers.dtype

dtype('int64')

In [9]:
smallerIntegers = np.array(integers, dtype = np.int8)
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [10]:
integers.nbytes

40

In [11]:
smallerIntegers.nbytes

5

In [12]:
overflow = np.array([127,128, 129], dtype=np.int8)
overflow

/var/folders/y4/12q38qbd5hs7h8842l8c6h3m0000gn/T/ipykernel_45686/3132148696.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  overflow = np.array([127,128, 129], dtype=np.int8)
/var/folders/y4/12q38qbd5hs7h8842l8c6h3m0000gn/T/ipykernel_45686/3132148696.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  overflow = np.array([127,128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

In [13]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])
print(floats)

[1.2 2.3 3.4 5.1 8.3]


In [14]:
floats.dtype

dtype('float64')

### Multidimensional arrays

<img src='mult_arrays.png' alt='mult_arrays' width=400>

In [15]:
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
nums[0][0]

1

In [17]:
nums[1,4]

10

In [18]:
nums.ndim

2

In [19]:
multi_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
multi_arr[1,0,2]

9

### Creating arrays from Lists and other Python structures

In [21]:
first_list = [1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [22]:
first_arrays = np.array(first_list)
first_arrays

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
second_list=[1,2,3,-1.23,50,128000.56,4.56]

In [24]:
second_array=np.array(second_list)

In [25]:
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [26]:
second_array.dtype

dtype('float64')

In [27]:
third_list = ['Ann',111111,'Peter',111112,'Susan',111113,'John',111114]

In [28]:
third_array=np.array(third_list)

In [29]:
third_array

array(['Ann', '111111', 'Peter', '111112', 'Susan', '111113', 'John',
       '111114'], dtype='<U21')

In [30]:
first_tuple = (5,10,15,20,25,30)

In [31]:
array_from_tuple=np.array(first_tuple)

In [32]:
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [33]:
array_from_tuple.dtype

dtype('int64')

In [34]:
multi_dim_list=[[[0,1,2], [3,4,5]], [[6,7,8],[9,10,11]]] 

In [35]:
arr_from_multi_dim_list=np.array(multi_dim_list)

In [36]:
arr_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Intrinsic Numpy array creation

In [37]:
integers_array = np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
second_array=np.arange(100,130)
second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [39]:
third_array=np.arange(100,130,2)
third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128])

In [40]:
floats_arr=np.linspace(10,20)
floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [41]:
floats_arr=np.linspace(10,20,5)
floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [42]:
rand_arr=np.random.rand(10)
rand_arr

array([0.32362532, 0.21279939, 0.56597325, 0.92436767, 0.79581427,
       0.54057081, 0.74537904, 0.01348526, 0.3998149 , 0.25714226])

In [43]:
rand_arr=np.random.rand(4,4)
rand_arr

array([[0.10492203, 0.34467701, 0.53045833, 0.56498122],
       [0.48220091, 0.95711543, 0.74096815, 0.64943688],
       [0.49107761, 0.94347993, 0.15014598, 0.86878974],
       [0.6522726 , 0.43169291, 0.15931787, 0.6017148 ]])

In [44]:
rand_arr=np.random.randint(0,100,20)
rand_arr

array([76, 73, 56, 93, 73, 75, 81,  2, 90, 72, 50, 95, 71, 74, 46,  5, 46,
       48, 68, 87])

### Creating arrays filled with constant values

In [45]:
zeros_array = np.zeros(5)
zeros_array

array([0., 0., 0., 0., 0.])

In [46]:
zeros_array=np.zeros((4,5))
zeros_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
ones_array=np.ones(6)
ones_array

array([1., 1., 1., 1., 1., 1.])

In [48]:
ones_array=np.ones((7,8))
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [49]:
ones_array=np.ones((4,5),dtype=int)
ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
fill_array=np.empty(10,dtype=int)
fill_array.fill(12)
fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [51]:
full_array=np.full(5,10)
full_array

array([10, 10, 10, 10, 10])

In [52]:
full_array=np.full((4,5),8)
full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

### Finding the shape and size of an array

In [53]:
first_arr=np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
second_array=np.linspace((1,2),(10,20),10)
second_array

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])