# Numpy Introduction

### Array types and Creating Numpy Arrays

In [2]:
import numpy as np

In [4]:
integers = np.array([10,20,30,40,50])

In [6]:
print(integers)

[10 20 30 40 50]


In [7]:
integers[0]

10

In [8]:
integers[0] = 20
integers

array([20, 20, 30, 40, 50])

In [9]:
integers[0] = 21.5
integers

array([21, 20, 30, 40, 50])

In [10]:
integers.dtype

dtype('int64')

In [11]:
smallerIntegers = np.array(integers, dtype = np.int8)
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [13]:
integers.nbytes

40

In [15]:
smallerIntegers.nbytes

5

In [17]:
overflow = np.array([127,128, 129], dtype=np.int8)
overflow

/var/folders/y4/12q38qbd5hs7h8842l8c6h3m0000gn/T/ipykernel_67870/3132148696.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  overflow = np.array([127,128, 129], dtype=np.int8)
/var/folders/y4/12q38qbd5hs7h8842l8c6h3m0000gn/T/ipykernel_67870/3132148696.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  overflow = np.array([127,128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

In [18]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])
print(floats)

[1.2 2.3 3.4 5.1 8.3]


In [19]:
floats.dtype

dtype('float64')

### Multidimensional arrays

<img src='mult_arrays.png' alt='mult_arrays' width=400>

In [21]:
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
nums[0][0]

1

In [24]:
nums[1,4]

10

In [25]:
nums.ndim

2

In [28]:
multi_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
multi_arr[1,0,2]

9